### ISSUE TITLE
ApiGen 5 is way slower than 4

### ISSUE THREAD

**Issue by nijel** [ApiGen/ApiGen#1015]
When using ApiGen 5, I've noticed it's way slower than 4 used to be. Actually speed and low memory usage was primary reasons for us using ApiGen and those seem to be gone with upcoming release. 

On [phpMyAdmin's SQL Parser](https://github.com/phpmyadmin/sql-parser) it's more than 250 times slower (from 2.5 seconds to 622 seconds). The memory usage went 16 times up (from 80 MB to 1.2 GB). This is simply blocker for us.

For ApiGen 5:

```console
$ /usr/bin/time -v ./vendor/bin/apigen generate --destination doc src/
Parsing reflections (this may take a while)... done!
Generating documentation...
 176/176 [============================] 100% 10 mins/10 mins 1.2 GiB. done!
Your documentation has been generated successfully!
	Command being timed: "./vendor/bin/apigen generate --destination doc src/"
	User time (seconds): 622.56
	System time (seconds): 10.27
	Percent of CPU this job got: 99%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 10:33.63
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 1286468
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 5661
	Voluntary context switches: 14
	Involuntary context switches: 26994
	Swaps: 0
	File system inputs: 0
	File system outputs: 12856
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0

```

ApiGen 4:

```console
$ /usr/bin/time -v ./vendor/bin/apigen generate --destination doc --source src/
Scanning sources and parsing
Found 80 classes, 0 constants and 0 functions
Generating API documentation
100 % - Finished!
	Command being timed: "./vendor/bin/apigen generate --destination doc --source src/"
	User time (seconds): 2.42
	System time (seconds): 0.05
	Percent of CPU this job got: 99%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:02.49
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 79488
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 2742
	Voluntary context switches: 2
	Involuntary context switches: 142
	Swaps: 0
	File system inputs: 0
	File system outputs: 13448
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```

**Comment by dga26** [comment]
hi @nijel 
i have the same problem on master branch.
on Windows memory grows up dangerously only for 2 directories parse.

From 100mo to more than 4go not reaching the end of the apigen generation step...

Regards

(i use github clone of the project)

**Comment by TonyBogdanov** [comment]
+1 for this.

I have a project of 6 PHP classes, yeah 6, and generating docs for them takes more than a minute on Windows (and my setup is pretty solid, it's no potato PC) with ~400MB RAM. If I also include the tests folder (another 6 files) it runs for about 16 minutes up to around 48%, RAM spikes up to 1.6 GB and then it just dies complaining that class X does not exist (X is different each time).

Maybe there's some kind of monstrous recursion or some other limit being reached?

Either way ApiGen 5 is simply useless at this point, to add to that I don't see any options for the `generate` command whatsoever, or at least some docs for the `apigen.yml` configuration.

And yeah, I know version 5 is still RC, but I am unable to make `4.1.2` run either due to so many deprecated packages and conflicts. Even on completely clean install (even with the `--debug` option) it goes through `Scanning sources and parsing` then immediately `Unexpected token found.` and dies with no other info available.

**Comment by Vitexus** [comment]
![obrazek](https://user-images.githubusercontent.com/2621130/90282575-e223fe80-de6e-11ea-835f-3b2d866bd114.png)

https://github.com/Spoje-NET/php-flexibee

:disappointed:

**Comment by JanTvrdik** [comment]
https://github.com/ApiGen/ApiGen/releases/tag/v7.0.0-alpha should be significantly more efficient, so performance should no longer be an issue.
