### ISSUE TITLE
debug info needed

### ISSUE THREAD

**Issue by patrickmj** [ApiGen/ApiGen#1022]
Trying to run it on the composer info listed in the README:

```
./vendor/bin/apigen generate -vvv application/src vendor --destination /var/www/html/omekas4docs/apigendocs
Parsing reflections (this may take a while)...Killed

```

So, with `-vvv` there's no debug info. That leaves me stuck. I caught some other things, but I'm a bit at a loss of how to proceed.

I saw the message about needing a maintainer. Unfortunately, I can't do that right now. This kinda means we'll need to move to a different doc generator. Or, or likely, just tell people to use the doc help in their IDE, which seems to be where things are moving.

**Comment by jordanbrauer** [comment]
Hi @patrickmj!

A quick search of the source-code for any of the following methods yields no results.

* `isVerbose()`
* `isVeryVerbose()`
* `isDebug()`

This means there is no verbose/debug output to print. What sort of information are you looking to find in the debug output? We can start by implementing that 🙂

**Comment by patrickmj** [comment]
It currently gives info about where in the ApiGen or Roave code things break down,  but not about where in the src code there's a documentation problem to fix. That would be super helpful, if possible

**Comment by mrtndwrd** [comment]
I'm specifically missing:

- Which file is currently being parsed. This would be very helpful, because I have some poorly documented code resulting in a lot of different `InvalidArgumentException`s. The only think I can do is `grep` for the (in my case) "invalid Fqsen" that is shown to me (for example: `"\string$date" is not a valid Fqsen."). It would be nice if the debug info would have printed the file it was parsing when encountering this error.
- Maybe a bit more information could be printed when an error is encountered. Right now, with debug enabled, I'll get a stacktrace. But, for example, I have no idea what the arguments of the function calls were.
- A typical debug print would be the configuration options that have been read. This would, for example, also greatly aid debugging issues like #1025

**Comment by JanTvrdik** [comment]
Should be resolved since https://github.com/ApiGen/ApiGen/releases/tag/v7.0.0-alpha.
