### ISSUE TITLE
Include further file extensions

### ISSUE THREAD

**Issue by chseip** [ApiGen/ApiGen#1030]
How do I get ApiGen to go through other extensions than `*.php` as well? For example to look in `*.module` (Drupal-specific PHP extension) files as well.
If so, can I specifiy this in the config file (c.f. #1029)?

**Comment by JanTvrdik** [comment]
Since https://github.com/ApiGen/ApiGen/releases/tag/v7.0.0-alpha this is possible with `--include` option. Note that this will override the default `*.php` mask so if you want to add `*.module` you need to specify the option twice, i.e.

~~~bash
apigen --include '*.src' --include '*.module' src --output docs
~~~
