### ISSUE TITLE
visibility_levels options is not working

### ISSUE THREAD

**Issue by vipinjn24** [ApiGen/ApiGen#1045]
visibility_levels options is not working as i have all 3 levels selected and i can only see public variables and methods.

**Comment by JanTvrdik** [comment]
`visibility_levels` option no longer exists since [7.0.0-alpha](https://github.com/ApiGen/ApiGen/releases/tag/v7.0.0-alpha). You can use `excludeProtected` and `excludePrivate` configuration options in `apigen.neon` to achieve the same effect.

See list of supported [configuration options](https://github.com/ApiGen/ApiGen#configuration) in readme.
