### ISSUE TITLE
Feature Request: includeTagged

### ISSUE THREAD

**Issue by ondrejmirtes** [ApiGen/ApiGen#1075]
In PHPStan I rather whitelist classes/elements to include in BC-covered area with `@api` instead of blacklisting them with `@internal`.

My rules are described here, but it's pretty easy: https://phpstan.org/developing-extensions/backward-compatibility-promise

* There are `@api` classes - all of their methods are part of API, these classes can be extended too
* There are `@api` interfaces - all of their methods are part of API, these interfaces can be implemented/extended too
* Some classes/interfaces are not `@api` but have `@api` methods - these are part of the API too
* Constructors in `@api` classes are excluded from the API unless they have `@api` too

So the only weird thing are constructors, I can live with that even if they're interpreted wrongly.

Thank you!

**Comment by ondrejmirtes** [comment]
FYI I'm gonna use the ApiGen 7 to generate an `apiref.phpstan.org` website, I'm excited about it :)

**Comment by JanTvrdik** [comment]
This is sort-of currently possible, if you provide your own [ApiGen\Analyzer\Filter](https://github.com/ApiGen/ApiGen/blob/v7.0.0-alpha/src/Analyzer/Filter.php) implementation by replacing `analyzer.filter` service in `apigen.neon`.

The only tricky/unsolved part, is how to get your filter class loaded, because both Docker and Phar versions have their own autoloaders and will never load your code. So you currently either need to install ApiGen with `composer require apigen/apigen:^7.0@alpha` or use some trick to make your filter class loadable.

**Comment by ondrejmirtes** [comment]
Oh yeah, custom Filter implementation is ideal for me. I'll run it in GitHub Actions so I'll create a subdirectory with its own composer.json in phpstan-src, no problem! 👍

**Comment by JanTvrdik** [comment]
@ondrejmirtes Let me know if you encounter any issues. You're the first one trying this out.

**Comment by ondrejmirtes** [comment]
And it's alive :) https://apiref.phpstan.org/1.8.x/namespace-PHPStan.html

And I started linking the ApiGen-generated reference instead of GitHub sources :) https://github.com/phpstan/phpstan/commit/b2f24ae6d7811fd494a10a336fc104c5412fb34e

And the whole website is already linked in the sidebar here :) https://phpstan.org/developing-extensions/extension-types

I really appreciate what you did here, I was able to take advantage of it immediately.

I have some feature requests but I'm gonna open separate issues for those.

**Comment by ondrejmirtes** [comment]
FYI the whole GitHub Action that builds this and deploys this: https://github.com/phpstan/phpstan-src/blob/1.8.x/.github/workflows/apiref.yml
