### ISSUE TITLE
Theme Documentations

### ISSUE THREAD

**Issue by chez14** [ApiGen/ApiGen#1095]
Hi ApiGen,

I noticed that there's no current official documentation on making themes besides following deprecated sample repo/package:
- https://packagist.org/packages/apigen/theme-bootstrap

Is there any past documentations that I can use/refer to?

Thank you!

**Comment by JanTvrdik** [comment]
> Is there any past documentations that I can use/refer to?

No. If if want to write it in [Latte](https://latte.nette.org/), it should enough to provide path to the theme directory with `--theme` in CLI or `themeDir` parameter in config file. In theme directory you may override any of the existing `*.latte` files (if a file exists exists in theme directory, it is used, otherwise the default one is used).

If you want to write it different technology, you would need to implement [Renderer](https://www.apigen.org/ApiGen/ApiGen.Renderer.html) interface.

**Comment by chez14** [comment]
Noted! 

Another quick question: is the deprecated theme package I mentioned earlier still relevant to current alpha version of ApiGen?

Thanks!

**Comment by JanTvrdik** [comment]
> is the deprecated theme package I mentioned earlier still relevant to current alpha version of ApiGen?

No. It is completely outdated and incompatible.

**Comment by chez14** [comment]
Noted. Thank you!

I'll close this issue since all of my questions has been answered.

Thank you.
