### ISSUE TITLE
@subpackage uses period (.) AND underscore (_) as package delimiter

### ISSUE THREAD

**Issue by clphillips** [ApiGen/ApiGen#204]
Given 

``` php
@package mypackage
@subpackage mypackage.sub_package
```

ApiGen creates package structure as mypackage > sub > package, instead of the expected mypackage > sub_package.

I think it's great the ApiGen tries to automatically resolve packages using the old Zend file name convention, but if we explicitly define a package and subpackage we expect it to literally be that.

If nothing else, can't we have a config setting to control the package delimiters for our projects?

**Comment by JosephLeedy** [comment]
I'd like to request this feature as well because I use underscores to separate proper nouns in my packages and backslashes for namespaces. Unfortunately the server that I am coding for is on an old version of PHP without support for proper namespaces, so that is my work-around.

This could be implemented as a configuration option that allows package separators to be defined.
