### ISSUE TITLE
PHP 5.6 "use function ..." leads to parse error

### ISSUE THREAD

**Issue by sophie-h** [ApiGen/ApiGen#495]
I get an  "Imported namespace name could not be determined." message if the code contains a "use function ..." statement. This feature has been introduced in 5.6 [1]

[1] http://php.net/manual/en/language.namespaces.importing.php

**Comment by TomasVotruba** [comment]
Just to let you know, issue is related to deprecated package https://github.com/Andrewsville/PHP-Token-Reflection

I'm working on it's replacement [ElementReflection](https://github.com/ApiGen/ElementReflection), where all features up to PHP 5.6 should be supported. It takes a while to rewrite whole packages, so I apologize for the delay.

**Comment by nozavroni** [comment]
I rely on ApiGen for my API docs so I really need this to work. I can't even switch to the other option I was considering for my API docs because it relies on the same library (PHP Token Reflection). Is there anything I can do to help move this along? Perhaps I could help you with some code? Let me know, thanks! :)

**Comment by TomasVotruba** [comment]
@nozavroni Sorry for late answer. We're working on replacement of reflection library.

**What would really help us is failing test with minimal failing code.** Could you send one please?

**Comment by TomasVotruba** [comment]
Resolved in ApiGen 5.x, where variadic is parsed by [Nikic/PHP-Parser](https://github.com/nikic/PHP-Parser) nicely.
