### ISSUE TITLE
Feature for an attribute filter in the generated docs

### ISSUE THREAD

**Issue by feamsr00** [ApiGen/ApiGen#512]
Hi,
Add some type of tag filter to support showing all (perhaps constrained by class) elements that have an, for example, @api tag.

This could be considered related to #339

-Thanks

**Comment by TomasVotruba** [comment]
Hi, this could be easy to add because similar function already has @todo and @deprecated filter.

See: https://github.com/apigen/apigen/blob/master/src/ApiGen/Generator/TemplateGenerators/DeprecatedGenerator.php

It could be handy to abstract it's function to "FilteredByAnnotationGenerator", where "deprecated" would be passed.

Could you propose PR to discuss over?

**Comment by TomasVotruba** [comment]
Implemented via #539
