### ISSUE TITLE
Replace MarkdownExtra with CommonMark

### ISSUE THREAD

**Issue by TomasVotruba** [ApiGen/ApiGen#547]
- more up-to-date
- less wtf
- see: https://github.com/ApiGen/ApiGen/pull/290

### Related issues:

- #543 
- #426
- #541

**Comment by miclf** [comment]
Hello @TomasVotruba,

Since you decided to switch to the Markdown format, why not take the extra step and use the standard and well-specified Markdown flavor that the community has been working on in the recent months? I’m of course talking of [CommonMark](http://commonmark.org/).

The PHP League has an actively package to handle it: [league/commonmark](https://github.com/thephpleague/commonmark/). It’s following the specification as closely as possible. Which is really nice, because it means we finally have a hope to end the total mess that Markdown has become in the past few years because of the dozens of different flavors that have been built.

**Comment by fprochazka** [comment]
:+1: for CommonMark. The league package looks nice.

**Comment by TomasVotruba** [comment]
Seems solid. PR with CommonMark is appreciated.

**Comment by TomasVotruba** [comment]
Not priority.

**Comment by TomasVotruba** [comment]
@jadb Please reopen as new owner. It's not mine issue anymore and I want those remove out of my active issues board.
