### ISSUE TITLE
@see description only works for url not methods

### ISSUE THREAD

**Issue by ofbeaton** [ApiGen/ApiGen#602]
I'm probably missing something, but I was trying to follow [PSR-5 @see description syntax](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#816-see) and could not get it to work for methods.

None of these work (note that not all of them are valid PSR-5 notation):
- `@see method my custon description` does not work
- `@see method() my custon description` does not work
- `@see class::method my custon description` does not work
- `@see \namespace\class::method my custon description` does not work

But it works for URLs:
- `@see https://someurl/ my custon description` works

If I'm missing something, as I am a beginner with this, apologies.

**Comment by samuele-artuso** [comment]
I agree, `@see` doesn't seem to be properly supported.
+1 for this issue.

**Comment by TomasVotruba** [comment]
Could you prepare PR?

**Comment by ctrlaltca** [comment]
I stumbled upon this bug today, in my case inside the main description of a class:
Code: https://github.com/pradosoft/prado/blob/33411471b407cce9bb3da883908887a5e4201c12/framework/Web/THttpSession.php#L58
Result: http://pradosoft.github.io/docs/manual/class-THttpSession.html (just after the first code block)

I found out that getting the `{@see }` blocks recognized is quite easy, just patching [line 267 of UrlFilters.php](https://github.com/ApiGen/ApiGen/blob/master/src/Templating/Filters/UrlFilters.php#L267) to read

```php
list($url, $description) = Strings::split($matches[1]);

- if ($link = $this->resolveLink($matches[1], $reflectionElement)) {
+ if ($link = $this->resolveLink($url, $reflectionElement)) {
    return $link;
}
```

The main problem is having the description as the link text instead of the original element name. This is quite hard to be done seeing how the code is structured now, heres the call stack:
```php
private function UrlFilters::resolveLinkAndSeeAnnotation($text, ElementReflectionInterface $reflectionElement)
public function UrlFilters::resolveLink($definition, ElementReflectionInterface $reflectionElement)
private function UrlFilters::createLinkForElement($reflectionElement, array $classes)
public function ElementLinkFactory::createForElement(ElementReflectionInterface $element, array $classes = [])
private function ElementLinkFactory::createForMethod(MethodReflectionInterface $reflectionMethod, array $classes)
public function LinkBuilder::build($url, $text, $escape = true, array $classes = [])
```
The idea of modifying all the methods signature in order to add an optional description parameter is bad, since most of the methods are public and the change would affect other code using these methods.

Using `ElementUrlFctory` to generate the url and Calling `LinkBuilder::build()` directly is a possibility, but it will lead to code duplication with `ElementLinkFactory` which is bad, too.

Devs: If you have any suggestion on your preferred way to modify the code in order to get this working, i'll be glad to submit a PR.

**Comment by ek9** [comment]
Perhaps it's best to put this to 5.x as it might possibly require some API breaks in order to implement properly and it's not something we should do at the last stages of 4.2.x

**Comment by TomasVotruba** [comment]
Since 5.x ApiGen will use [phpDocumentor/ReflectionDocBlock](https://github.com/phpDocumentor/ReflectionDocBlock) package for work with tags.

In short, it means:

- `@see` for reflection elements (class, function, property...)
- `@link` for urls

I like it, because it makes clear difference between them and states exclusive uses case for each annotation.

**Comment by tractorcow** [comment]
Thank you so much @TomasVotruba !

**Comment by TomasVotruba** [comment]
Thank you :)
