### ISSUE TITLE
Phar and license issue

### ISSUE THREAD

**Issue by remicollet** [ApiGen/ApiGen#675]
The apigen.phar contains a lot of libraries.

From the symfony LICENSE (only an example, other libraries are also concerned)

```
 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.
```

Which means that as you don't include the LICENSE files in the .phar, you violates the license terms.

**Comment by remicollet** [comment]
More information on https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text

     Common licenses that require including their texts with all derivative works include ASL 2.0, EPL, BSD and MIT.

**Comment by feamsr00** [comment]
So this seemed worth while to look into. It seems that due to Box's configuration only .php files (i.e. no txts) are included in the phar, *with the exception of .\LICENSE*. Most of the licenses included (inventory below) have no requirement *where* the notice goes, just that it goes. As such, ApiGen could easily just add those notices in .\LICENSE and be technically compliant. It might, however, be more "kosher" to dump them all on a "-V" option.

License Inventory: https://www.versioneye.com/user/projects/56596a41a174a8000b001248#tab-licenses
BoM: [28_11_2015_apigen-apigen.pdf](https://github.com/ApiGen/ApiGen/files/46308/28_11_2015_apigen-apigen.pdf)

Side note. All the included packages are MIT compatible *except* fshl. Considering its copyright  (and thus its license) is [tied up in absentia of its owner](https://github.com/kukulich/fshl/issues/4), it might be wise to swap it with another compatible component.

**Comment by remicollet** [comment]
Shouldn't adding  "LICENSE" to box.json be enough ?

    -	"name": ["*.php", "*.json", "*.latte", "*.neon", "*.css", "*.js", "*.png"],
    +	"name": ["*.php", "*.json", "*.latte", "*.neon", "*.css", "*.js", "*.png", "LICEN*"],

**Comment by feamsr00** [comment]
That would work indeed. Question is whether this issue was suggested just to get ApiGen into "compliance"? Or was this issue suggested to get some particular license notice showing up somewhere?

**Comment by remicollet** [comment]
> Question is whether this issue was suggested just to get ApiGen into "compliance"? 

Yes, only for compliance. As other projects do (phpunit, composer, ...)

> Or was this issue suggested to get some particular license notice showing up somewhere?

Not the subject here, but phpunit implements an "manifest" option which list libraries included in the .phar. Doesn't really improve license visibility but seems a good idea.

**Comment by jadb** [comment]
Hey thanks for bringing this to my attention. Do you want to help fix it?

**Comment by jankal** [comment]
Closed. PHAR not supported since #788.
