### ISSUE TITLE
Make future-proof

### ISSUE THREAD

**Issue by jankal** [ApiGen/ApiGen#782]
# Future-proof is key for not burying this project any time soon

So hello. As I've been using ApiGen privately for 1.5 years now, I really see the need to modernize it. Else it will be dead (as @phenixiim already realized in #771). Therefor we probably need to drop backwards compatibility for PHP 5 for the next releases.

For all the BC lovers: Users should still be able to use an older version supporting PHP 5.

I will from now on start with contributing to this project (yep: @ek9 #779). For this the following list of tasks need to be done to get this future-proof.

Maybe someone part of the org (@jadb @kukulich) could add a [GitHub project](https://github.com/ApiGen/ApiGen/projects) for that and import this list then.

Moved list to repo (https://github.com/ApiGen/todolist/blob/master/new-version.md)

For any other ideas: feel free adding them as a comment so the community and also the contributors (including me) can work on it.

I really don't like the idea of burying this project as it has a very huge codebase and is the outcome of many peoples work with as I see probably thousands of lines of code. Haveing roud 580 tests is very impressive. We will keep this up and make it better.

Pepole who volunteered for contributing:
 - @TomasVotruba 
- @nozavroni #495

**Comment by TomasVotruba** [comment]
#### Thanks for putting this down!

I'd also recommend to bumping to PHP 7.1. 
Really helped me with not burying my projects.

Can help if needed. I'm quite fast with it :)

**Comment by jankal** [comment]
@TomasVotruba Do you have any permissions on this repo?

**Comment by TomasVotruba** [comment]
@jankal I don't this so.

**Comment by jankal** [comment]
@TomasVotruba see #779

**Comment by TomasVotruba** [comment]
Just a thought. I'm thinking about removing Markdown, since it brings so various syntax problems and **encourages people to actually use Markdown in PHP comments**.

I consider this mixing of concerns. Docblock should be used for information, not for writing posts - blogs are for that. It would lighten this project a bit more.

What do you think? Do you have some use cases where this is needed?

**Comment by TomasVotruba** [comment]
Another idea is for dropping **tree** support. I never really used and it just show all classes. I think it's same use as showing all posts on blog. I look for particular class and it's relations, not to see it all.

What do you think?

**Comment by jankal** [comment]
@TomasVotruba Will put this into a GitHub Proejct now.

**Comment by ek9** [comment]
Small comment regarding version bumps:

It would be best to have version of apigen release for all PHP version, so we at least have one version series for 7.0. For this, it's important to not skip these versions and have apigen usable. If one now would skip 7.0 and go straight for `7.1`, then developers trying to get this running on PHP `7.0` would have problems installing it.

My suggestion would be to bump the minor version number every time we up the PHP version requirement. As an example:
- `4.1` - at this point legacy released version
- `4.2` - PHP 5.6 / PHP 7.0
- `4.3` (or `5.0`) - PHP 7.0+
- `4.4` (or `5.1`) - PHP 7.1+

We do not have to maintain these versions, however it would still be possible for someone to submit a patch against specific version.

**Comment by TomasVotruba** [comment]
It would make sense, if ApiGen would be able to analyze PHP 5.5+ code. 

It' is not at the moment, so this would be just releasing various broken versions that could run on any PHP, yet analyzing only PHP 5.4- code. Is that desired feature?

**Comment by ek9** [comment]
> It would make sense, if ApiGen would be able to analyze PHP 5.5+ code.
>
> It' is not at the mome
I am not sure I understand your statement. What is the difference between PHP 5.5 and PHP 5.4 code that apigen is unable to analyze?

**Comment by TomasVotruba** [comment]
ApiGen breaks, when analyzing PHP 5.5+ code at the moment.

**Comment by ek9** [comment]
> It' is not at the moment, so this would be just releasing various broken versions that could run on any PHP, yet analyzing only PHP 5.4- code. Is that desired feature?
>
> ApiGen breaks, when analyzing PHP 5.5+ code at the moment.

I am sorry but this just further confuses things. I have components who have been migrated from PHP 5.4 to 5.6 through the years and I have been using ApiGen to generate API for them. The same code runs on PHP 7.0 too. Perhaps it does not support all of the new features, but not everyone is relying on them.

I have been using apigen 4.1 and `dev-master` just fine and haven't encountered much problems.

**Comment by TomasVotruba** [comment]
If you don't thinks those issues are valid, please test them and report for closing. I'd be happy to close them.

**Comment by ek9** [comment]
> f you don't thinks those issues are valid, please test them and report for closing. I'd be happy to close them.

Which issues do you mean specifically?

**Comment by TomasVotruba** [comment]
Those I linked above

**Comment by ek9** [comment]
Ok I think I've found what you mean:
- https://github.com/ApiGen/ApiGen/issues?q=is%3Aopen+is%3Aissue+label%3Adue-to-tokenreflection

More specifically, I made sure the PHP5.6 are tagged correctly, so for PHP 5.6 only: https://github.com/ApiGen/ApiGen/issues?q=is%3Aopen+is%3Aissue+label%3A%22PHP+5.6%22

I believe all these issues we target for 5.0 rewrite. The 4.2.x will be released as a final version of 4.x series (I can maintain any quick-fixes until 5.0). We focus all the work on the rewrite, I just want to make sure that the years worth of commits (that were previously on master as `4.2.0.x-dev` get released) as they were working correctly.

While the specific features aren't fully supported, the previous ApiGen version were released (4.0, 4.1 etc.). The 4.2 is for projects who were already depending on apigen, but can no longer run 4.1 due to it being outdated.

I will help you with the refactoring once I can sort out the 4.2.
