### ISSUE TITLE
apigen version 5.x

### ISSUE THREAD

**Issue by StephanKrauss** [ApiGen/ApiGen#878]
Hello,

how can i get a version 5.x from apigen ?

Your sincerly

Stephan

**Comment by TomasVotruba** [comment]
Hey @StephanKrauss ,

this version is not released yet. You can try @dev version for now.
Just install `composer require apigen/apigen:@dev`

**Comment by Ximich** [comment]
Do you have any dates for 5.x RC1 release? 
Use @dev version on production projects isn't good solution.

**Comment by TomasVotruba** [comment]
Probably next week, but lot of work is required for final release. Mainly bug reports and fixes, because many template elements are not tested.

**I'll probably release RC1 soon, so get faster feedback from you and make smaller itterations.**

What do you think?

**Comment by POPSuL** [comment]
@TomasVotruba RC1 should be released after #877 resolving. I can't test apigen without solving that issue.
But, I think this issue was be solved tomorrow ;) At least I hope...

**Comment by Ximich** [comment]
Small and fast iterations works fine for me! I promise test my project (with a couple of own templates) on RC1.

**Comment by TomasVotruba** [comment]
Thank you guys, it means a lot to me. 

Waiting on #877 makes sense.

**Comment by TomasVotruba** [comment]
I've prepare Roadmap for 5.x release in Github project, so everyone knows, what is needed for release: https://github.com/ApiGen/ApiGen/projects/3

**Comment by TomasVotruba** [comment]
There are many new quesions about 4.x release, because it's the last stable and no tag in sight. Also new README doesn't imply there is or will be any new version.

@POPSuL Looks like your PR will require more time to merge, so in meantime I'll release 5.0.0-RC1 with README update, to let people now and to gather feedback faster.

Don't worry, I'll still wait on more bugs to solve. I expect RC2/3/4.
