### ISSUE TITLE
Any plans for left sidebar?

### ISSUE THREAD

**Issue by vlastavesely** [ApiGen/ApiGen#948]
I always liked the left sidebar in the API reference. Why the new version does not have"this feature? Any reason for it?

I mean this: http://www.doctrine-project.org/api/orm/2.5/namespace-Doctrine.ORM.html

**Comment by TomasVotruba** [comment]
Thanks for asking this good question. Instead of looking for the PR, I'll write them down here.

Actually, there were many design and architecture reasons:
 
### Design Reasons

- sidebar was jumping, as it used cookie to store last location
- javascript was manually written and difficult to use; tested would be probably fine
- broken on mobile, I always had to go to Github as replacement; which kinda kills main feature of using Twitter Bootstrap 
- see [Sami](https://api.symfony.com/3.3/index.html) on mobile
- it looked weird using responsive design :(
- on/off tree structure had magic behavior

### Architecture Reasons

- it duplicated most part of main page, that turned the attention from main page to the left
- it had magic behavior to display alements based on namespace, again duplicating main page
- this sometimes caused bugs when all classes, interfaces, traits and functions on the left didn't match the main page
- **current version focuses on search feature**, that is much faster compared to Sami and phpDocumentor
     - this is killer feature on mobile as well, as it is much faster then scrolling down the list of classes and looking for it manually (should be, I didn't test it yet)

All this was huge maintenance with nice-to-have design feature overhead, that ApiGen can't afford now. Because it's broken in so many cases that doesn't even produce a html version to miss this on.

**I think the right direction is to put all saved energy to a super friendly search input and autocomplete instead.** Like in PHPStorm already is.

**Comment by vlastavesely** [comment]
What a pity, I will miss it.

**Comment by TomasVotruba** [comment]
If there will be no major issues floods after 5.0 stable release, we could get back to this.
